### ISSUE TITLE
pulsed mode

### ISSUE THREAD

**Issue by fdurville** [pcDataSpider/SpiderScope#5]
A few things:
When selecting the pulsed experiment, there is no choice of analog input channel, nor choice of sampling rate.
It seems to work when you use the main window to enter the sample rate, start and stop the experiment. But at the end there is no save option popping up. You can still go to file/save menu in the Pulsed Experiment window, but it is not convenient.
Also, when you re-open the pulsed experiment to start another acquisition run, the sampling rate is reset at 2000 and CANNOT be changed.
I have not yet checked all the timings on the scope. This is my next task.

Timing is weird. When sampling rate in main window is above 1000, the ADC sampling seems well synchronized with the excitation / trigger pulse. But at lower speed, it not.

Also, it seems that the delay is not working.... I do not see any delay between the start of the excitation pulse and the ADC chip select (start of the ADC sampling). And the ADC appears to running continuously (does not stop after a given delay)....

FD

**Comment by pcDataSpider** [comment]
The points should no longer go back in time. Also, due to some fixes, there are less bad checksums. (there was a bug that occasionally miscalculated the checksum)

**Comment by pcDataSpider** [comment]
Fixed!
