### ISSUE TITLE
sampling rate

### ISSUE THREAD

**Issue by fdurville** [pcDataSpider/SpiderScope#6]
With latest version, under normal acquisition or pulsed experiment, the sampling rate can be set only once for each channel. Same goes for all parameters, delay and duration. Also, duration cannot be set after you stop the pulse experiment.

Also, from the main window, I was able to set sampling rate up to 40,000 per seconds, and it worked on the scope screen. But with pulsed experiment, sampling rate would not go over 10,000 per seconds (when entering 20,000 in the pulse experiment window, the measured rate on o-scope was only 10,000 per second and no message / error was displayed).

The STOP/RESTART button in pulse experiment windows works sometimes, but usually does not. The same applies for STOP/START from main window. It seems it works if you STOP before you set a new sampling rate....

ADC reading starts as soon as pulse experiment window is open - annoying.

**Comment by pcDataSpider** [comment]
Closed by changing to wxPython 2.8 instead of wxPython 3.0
